#!/bin/bash

# Deploy blue version (current)
kubectl apply -f blue_deployment.yaml

# Deploy green version (new)
kubectl apply -f green_deployment.yaml

# Apply service
kubectl apply -f kubeservice.yaml

# Check pods
kubectl get pods

# Check logs of green deployment
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD

